- name: install and run nginx
  hosts: mongodb
  tasks:
  - name: install nginx
    ansible.builtin.yum:
     name: nginx
     state: install
  - name: start nginx
    ansible.builtin.service:
     name: nginx
     state: started