- name: printed msg
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks: 
  - name: printed msg
    ansible.builtin.debug:
     msg: "i am learning is {{COURSE}} tariner is {{TRAINER}} and duration is {{DURATION}}"