- name: printed message
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
  - name: printed msg
    ansible.builtin.debug:
    msg: "i am learning {{COURSE}} course and trainer is {{TRAINER}} it will take duration {{DURATION}}"

