- name: printed massege
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
  - name: printed massage
    ansible.builtin.debug:
     msg: "i am learning {{COURSE}} my trainer is {{TRAINER}} it will take duration is {{DURATION}}"
