- name: printed message
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
  - name: print the course
    ansible.builtin.debug:
    content: "i am learning {{COURSE}} course and trainer is {{TRAINER}} it will take duration {{DURATION}}"

