- name: varibles from files
  hosts: mongodb
  vars_files:
  - varibles.yaml
  tasks:
  - name: printed varibles
    ansible.builtin.debug:
     msg: "i am learning {{NAME}}, trainer is {{TRAINER}} and duration is {{DURATION}}"