- name: printed varibles from prompt
  hosts: localhost
  vars_prompt:
   - name: USERNAME
     prompt: please enter username
     private: false
   - name: PASSWORD
     prompt: please enter password
     private: true
  tasks:
   - name: printed varibles
     ansible.builtin.msg:
      msg: "username {{USERNAME}} password{{PASSWORD}}"
