- name: install and run nginx
  hosts: mongodb
  tasks:
  - name: install nginx
    ansible.builtin.yum:
     name: nginx
     state: installed
  - name: nginx started
    ansible.builtin.service:
     name: nginx
     state: started