- name: varibles from prompt level
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    prompt: please enter password
    private: true
  tasks:
   - name: print prompt varibles
     ansible.builtin.debug:
      msg: "username {{USERNAME}} password {{PASSWORD}}"
