- name: printed massages
  hosts: mongodb
  become: yes
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
  - name: printed message
    ansible.builtin.debug:
    msg: "i am learning is {{COURSE}} trainer is {{TRAINER}} and duration is {{DURATION}}"