- name: printed varibles from play level
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
   - name: printed varibles from playlevel
     ansible.builtin.debug:
      msg: "i am learning course is {{COURSE}} tariner is {{TRAINER}} duration is {{DURATION}}"