- name: printed varibles from task level
  hosts: mongodb
  vars:
   COURSE: Devops
   TRAINER: swamy
   DURATION: 110hrs
  tasks:
  - name: print varibles from task level
    ansible.builtin.debug:
     msg: " iam learning course is {{COURSE}} and trainer is {{TRAINER}} and duration is {{DURATION}}"
  - name: print varibles and add overwrite files
    vars:
     HOUSE: own
    ansible.builtin.debug:
     msg: " iam learning course is {{COURSE}} and trainer is {{TRAINER}} and duration is {{DURATION}} and i have {{HOUSE}} house"
       