- name: install nginx and run
  hosts: mongodb
  tasks: 
  - name: install nginx
    ansible.builtin.yum:
     name: nginx
     state: installed
  - name: started nginx
    ansible.builtin.service:
     name: nginx
     state: started