- name: install and run nginx
  hosts: mongodb
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.yum:
     name: install nginx
     state: installed
  - name: start nginx
    ansible.builtin.service:
     name: start nginx
     state: started