- name: testing the varible precedence
  hosts: mongodb
  vars:
   NAME: swamy-play
  vars_files:
  - varibles44.yaml
  vars_prompt:
  - name: NAME-prompt
    prompt: please enter trainer
    private: false
  tasks:
  - name: print the varibles
  vars:
   NAME: swamy-task
   msg: "what is trainer name {{NAME}}"