- name: testing the varible precedence
  hosts: mongodb
  vars:
   NAME: swamy
  vars_files:
   varibles44.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter trainer
    private: false
  tasks:
  vars:
   NAME: swamy
  - name: print the varibles
  tasks:
  - name: testing the precedence varibles
    ansible.builtin.debug:
     msg: "what is trainer name {{NAME}}"