- name: testing the precedence of varibles
  hosts: mongodb
  vars:
   NAME: swamy-play
  vars_files:
   varibles44.yaml
  vars_prompt:
  - name: NAME-prompt
    prompt: please enter the name
    private: false
  tasks:
  - name: printe the varible at task level
    vars:
     NAME: swamy-task
  ansible.builtin.debug:
   msg: "what is trainer name {{NAME}}"